export enum GoodsType {
    Wood = "wood",
    Brick = "Brick",
    Grain = "Grain",
    Hemp = "Hemp",
    Wool = "Wool",
    RawMetal = "RawMetal",
    Honey = "Honey",
    Salt = "Salt",
    MetalGoods = "MetalGoods",
    Mead = "Mead",
    Cloth = "Cloth",
    Beer = "Beer",
    Stockfish = "Stockfish",
    Clothing = "Clothing",
    Cheese = "Cheese",
    Pitch = "Pitch",
    Pelts = "Pelts",
    Meat = "Meat",
    Wine = "Wine",
    Spices = "Spices",

    Cotton = "cotton",
    Sugar = "sugar",
    Tobacco = "tobacco",
    Silver = "silver",
    Gold = "gold",
    Gemstones  = "gemstones",
    Jewelry = "jewelry",
    Paper = "paper",    
    Coal = "coal",
    Steel = "steel",
    Oil = "oil",
  }